### ISSUE TITLE
Validation Issue ( form submissions)

### ISSUE THREAD

**Issue by AhemdMahmoud** [LeetStream/leetstream.github.io#1]
### - representation
![image](https://github.com/LeetStream/leetstream.github.io/assets/109467491/b685a5d4-f61a-48c7-9866-c7373345fb86)
![image](https://github.com/LeetStream/leetstream.github.io/assets/109467491/0fb4f563-006c-4549-8a16-c4e6cca3a15e)

**Comment by mohamed-sallam** [comment]
Great, I solved it, check it now!
`Your Solution` and `Note` aren't required.

**Comment by AhemdMahmoud** [comment]
Yes ,Solved😍
